import webbrowser
webbrowser.open("https://en.wikipedia.org/wiki/Portal:Current_events")
webbrowser.open("https://www.google.com")
webbrowser.open("https://www.google.co.in")
webbrowser.open("https://www.google.it")
webbrowser.open("https://www.google.fr")
webbrowser.open("https://www.abc.xyz")
webbrowser.open("https://www.wow.com")
webbrowser.open("https://www.aol.com")
webbrowser.open("https://en.wikipedia.org/wiki/Special:Random")
webbrowser.open("https://www.mayam.cc")
